---
- name: install webapp
  hosts: apps
  tasks:
    - name: create application file
      copy:
        src: 'files/idmeup.py'
        dest: '/usr/local/bin/idmeup.py'
      become: true
    - name: install flask
      apt:
        name: python3-flask
        state: present
      become: true
    - name: execute idmeup app
      shell: cd /usr/local/bin; nohup flask --app idmeup run --host 0.0.0.0 </dev/null >/dev/null &
