---
- name: install nginx and deploy a templated configuration
  hosts: https
  tasks:
    - name: install the nginx package
      apt: 
        name: nginx
        state: present
        update_cache: true
      become: true
    
    - name: push a configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true
    
    - name: manage the nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: true
  roles:
    - prometheus.prometheus.node_exporter

  

