---
- hosts: monitors
  roles:
  - role: 0x0i.grafana
  - role: prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - http:9100
        - app:9100
        - db:9100
